### ISSUE TITLE
User can select a cuisine

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can select a cuisine to view recipes for.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive page of icons that allow users to view a specific cuisine's recipes 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/192328758-5ef1d3e9-c458-4715-8e3d-900b7ff62cc4.png)
![image](https://user-images.githubusercontent.com/103452411/192331879-507ce4d2-9edb-4caa-8102-0c12864ea43b.png)

## ✅ Task List
- [x] Create necessary HTML, CSS and JavaScript files
- [x] Plan out page layout
- [x] Start with mobile view first, then the webpage view after 
   - [x] Media queries!
   - [x] Create necessary layout classes
   - [x] Create necessary utility classes
- [x] Create icons with the description
   - [x] Add and save the icon images into VS Code 
   - [x] Use CSS classes to align them, MEDIA QUERY for different views
- [x] The icons should have the JS to retrieve the data, just not showing the data yet
   - [x] Event listeners for users to be able to click for data
   - [x] Retrieve data from API using XMLHttpRequest
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
