### ISSUE TITLE
User can view their results

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their results.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a page showing the results of the cuisine the user clicked on. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/192386631-80beaf3c-fd60-48a9-8ae1-eff464e3adc6.png)
![image](https://user-images.githubusercontent.com/103452411/192422740-355c404f-9eee-4892-9ae2-50f904a435a6.png)

## ✅ Task List
- [x] Use view-swapping to show the other page with the clicked results
- [x] Title changes to event.target.getAttribute('data-id') + ' Dishes'
   - [x] Create a DOM tree with the information from API
   - [x] Make a div to contain each recipe which will contain
      - [x] button element
         - [x] img as child -> object.results[i].image becomes the picture 
      - [x] h5 element -> object.results[i].title becomes the description
      - [x] border-bottom on div container for easier reading (mobile view)
      - [x] also border-bottom on container also for webpage, but make sure there's no margin so it looks like 1 long line
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
