### ISSUE TITLE
User can verify recipe status

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can verify a recipe was saved to or removed from saved recipe page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a modal that pops up on top of the save/remove recipe button that shows a message and disappears after a few seconds.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/194176726-c0a867d1-002a-4bd8-b410-298d938908ce.png)

![image](https://user-images.githubusercontent.com/103452411/194176650-2731014a-328b-4533-bf5b-0fe6864bd5ed.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal container in javascript, where the button is created
  - [x] CSS - relative to where the save/remove button is 
  - [x] Create a function to check the data-id and show a different text content (success saved or removed)
- [x] Use setTimeout() to show the modal and make it disappear after 1-2 seconds
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
