### ISSUE TITLE
User can see more recipes

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#24]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see more recipes after clicking a button "See more"
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a button that says "See more" that will load 10 more recipes from search query and the button will disappear when there are no more additional recipes to show
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/194461140-fdc36a91-d71a-4874-8daa-98acd742fae6.png)
![image](https://user-images.githubusercontent.com/103452411/194461215-659ef375-9fc8-4350-8b93-15479c06c719.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Edit get function to call 100 search results
  - [x] All 100 of these search results will be stored in data model, data.searchResults
  - [x] Make a new function to only show 10 of these search results on page with DOM tree
- [x] Create a button that says "See More"
  - [x] Create addEventListener for button to show 10 more results stored in data.searchResults
  - [x] When there are no more results, have the button disappear
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
