### ISSUE TITLE
User can view a recipe

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the recipe they selected.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a page showing the recipe the user selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/192671853-eedbb7d8-ecdf-4720-b808-873ac5cb3b3f.png)
![image](https://user-images.githubusercontent.com/103452411/192671912-eb31ebd2-7af4-40ac-a41c-5be83661a507.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.
- [x] Use view-swapping to show the selected recipe
- [x] Create a DOM tree with the new information from API
   - [x] Make a div class selected-recipe-container
   - [x] Make a div class row (webpage: flex-direction row, mobile column)
      - [x] Img element Object.image
      - [x] div element class ingredients-list
         - [x] h3 element text content Ingredients 
         - [x] ul element 
            - [x] For loop to gather all the ingredients from array
            - [x] li text content ingredient names found at Object.extendedIngredients[i].name 
   - [x] Make a div class row instructions
      - [x] Another for loop here 
      - [x] h4 element text content = 'Step ' + Object.analyzedInstructions[0].steps[j].number
      - [x] p element text content = Object.analyzedInstructions[0].steps[j].step
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
