### ISSUE TITLE
User can save a recipe

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save the recipe they selected.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a save button which will save the recipe and link to the saved recipe page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/192837338-62c30558-de38-418f-b617-d8e195d1365f.png)
![image](https://user-images.githubusercontent.com/103452411/192837483-50479d56-c60a-46ba-8075-2414ae282302.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.
- [x] Make a save recipe button
   - [x] Get the bookmark icon from font awesome 
   - [x] Place the button on the same row as ingredient label 
- [x] Have the button remember the recipe ID on that page and save it to the local storage
- [x] The recipe ID will be stored in local storage
- [x] My recipe page should repopulate with XMLHttpRequest with the recipe IDs
   - [x] Only grab image and title and loop it almost with the same function as the DOM tree for the search page
   - [x] Change get URL to recipe ID, change the image and text content 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
