### ISSUE TITLE
User can view their saved recipes

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/feasting-eyes#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their saved recipes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a page of user's saved recipes, which can be accessed via modal.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/192905030-4a39d205-3491-4f0a-9623-48e088f23f17.png)
![image](https://user-images.githubusercontent.com/103452411/192904949-b3f1059c-b6c4-4152-8e06-6a9cbd4c1f75.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a modal container in index.html
   - [x] Modal gets X in the upper right corner
   - [x] 2 buttons with border bottom for easy reading
      - [x] Home Page
      - [x] My Recipe Box 
   - [x] Create a function to change the view to either the saved recipe page or the homepage depending on which one is clicked 
- [x] When the recipe box is clicked, the My Recipe Box page should populate with the saved recipeID in local storage
   - [x] Repopulate with XMLHttpRequest 
   - [x] Same layout as cuisine page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
